# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b5b745c6f8ebf7e789f173fa0a541c95030cfd715502c982f7bf11e752a28110bf359675a9b027ff34c7d3eb0366dccad3a1a43b6d890ad9c5db0b3f3b02c5c

test:
  secret_key_base: 8a56d403f64d891e278f1d940f800534107ee2c180d2618e8390d6e4585a008e7716673f2023191875a0b8d461ad0df49685358cdbf7ef3404a4ecb831b40939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
